using DifferentialEquations
using Plots, StatsPlots
using Distributions, Random, FFTW
using Turing, ReverseDiff, Memoization
using LinearAlgebra:Diagonal
using Base.Threads
using FileIO, JLD2
using LaTeXStrings
using DataFrames
using CSV

#parsing data generated by then gen functions to a csv file

x_axis = 0.1:0.1:5
true_mean_noise_t = (map(x-> (0.2 ./(1 .+ x)), x_axis))

function data_parse(data)
    mean_data = vec(mean(data, dims=1))
    return mean_data
end

#input the file that you saved in the gen script
data = FileIO.load("mixed_ratio_0.05.jld2", "data")

mean_noise_t = mean.(map(x-> x[:noise_ampl_t], data))'
std_noise_t = std.(map(x-> x[:noise_ampl_t], data))'

mean_ampl = mean.(map(x-> x[:ampl], data))'
mean_tau = mean.(map(x-> x[:tau], data))'
std_ampl = std.(map(x-> x[:ampl], data))'
std_tau = std.(map(x-> x[:tau], data))'

data = Dict(:ratio_mulitplicative_thermal => x_axis,
:mean_noise_thermal => vec(mean_noise_t),
:std_noise_thermal => vec(std_noise_t),
:mean_amplitude => vec(mean_ampl),
:mean_tau => vec(mean_tau),
:std_ampl => vec(std_ampl),
:std_tau => vec(std_tau),
:true_mean_noise_t => true_mean_noise_t)

CSV_data = DataFrame(data)


CSV.write("mixed_ratio_0.05", CSV_data)